name: groswap
description: "Resourcely - Community Essentials App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Permissions
  permission_handler: ^11.3.1

  # Cloudinary
  cloudinary_public: ^0.9.0

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0

  # State management
  provider: ^6.1.2

  # UI + Icons
  cupertino_icons: ^1.0.8

  # Image picker (modern version)
  image_picker: ^0.8.7+4
  # Open phone dialer / URLs
  url_launcher: ^6.1.11

  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: 0.9.4
  # Carousel for product images
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.jpg
