// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFqt5oDWXBY86GZWpel0HAnPikdpaJ4o',
    appId: '1:1080808426200:web:f4873aecde993ff90ca5ad',
    messagingSenderId: '1080808426200',
    projectId: 'groswap-70246',
    authDomain: 'groswap-70246.firebaseapp.com',
    storageBucket: 'groswap-70246.firebasestorage.app',
    measurementId: 'G-MGSZ9QLGXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjX3YgSV96SnMO_DJBsm15SYh25No1H_k',
    appId: '1:1080808426200:android:784db7b354df4f180ca5ad',
    messagingSenderId: '1080808426200',
    projectId: 'groswap-70246',
    storageBucket: 'groswap-70246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzuk-ygA8wN6gW8u9ZPK9jdSKnEFir2tM',
    appId: '1:1080808426200:ios:9bac2a953878509d0ca5ad',
    messagingSenderId: '1080808426200',
    projectId: 'groswap-70246',
    storageBucket: 'groswap-70246.firebasestorage.app',
    iosBundleId: 'com.example.groswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzuk-ygA8wN6gW8u9ZPK9jdSKnEFir2tM',
    appId: '1:1080808426200:ios:9bac2a953878509d0ca5ad',
    messagingSenderId: '1080808426200',
    projectId: 'groswap-70246',
    storageBucket: 'groswap-70246.firebasestorage.app',
    iosBundleId: 'com.example.groswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEFqt5oDWXBY86GZWpel0HAnPikdpaJ4o',
    appId: '1:1080808426200:web:6d15ab996685a7b30ca5ad',
    messagingSenderId: '1080808426200',
    projectId: 'groswap-70246',
    authDomain: 'groswap-70246.firebaseapp.com',
    storageBucket: 'groswap-70246.firebasestorage.app',
    measurementId: 'G-L1C89DNQM1',
  );

}